# Generated by Django 4.0 on 2021-12-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
