# Generated by Django 4.0 on 2021-12-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_dashboard_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='monthly_capital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
