# Generated by Django 4.0 on 2021-12-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_dashboard_monthly_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('card_number', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.CharField(blank=True, max_length=200, null=True)),
                ('revenue', models.CharField(blank=True, max_length=200, null=True)),
                ('spent', models.CharField(blank=True, max_length=200, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('reciver', models.CharField(blank=True, max_length=200, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cards')),
                ('dashboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.CharField(blank=True, max_length=200, null=True)),
                ('is_paid', models.IntegerField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cards')),
                ('dashboard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dashboard')),
            ],
        ),
    ]
