# Generated by Django 4.0 on 2021-12-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_cards_transactions_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='dashboard_id',
            new_name='dashboard',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='dashboard_id',
            new_name='dashboard',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='dashboard_id',
            new_name='dashboard',
        ),
    ]
