# Generated by Django 4.0 on 2021-12-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_dashboard_id_cards_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
