# Generated by Django 4.0 on 2021-12-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_cards_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='type',
        ),
    ]
