# Generated by Django 4.0 on 2021-12-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_cards_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
