# Generated by Django 4.0 on 2021-12-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_dashboard_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
