# Generated by Django 4.0 on 2021-12-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_reminder_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_autopay',
            field=models.BooleanField(default=False),
        ),
    ]
