# Generated by Django 4.0 on 2021-12-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_reminder_is_autopay'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
