# Generated by Django 4.0 on 2021-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_transactions_status_alter_reminder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
