# Generated by Django 4.0 on 2021-12-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_transactions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
