# Generated by Django 4.0 on 2021-12-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_reminder_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='deposites',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
