# Generated by Django 4.0 on 2021-12-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_cards_deposites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
